### ISSUE TITLE
Error when trying to Login with Google using SonarQube 5.4

### ISSUE THREAD

**Issue by fhperuchi** [steven-turner/sonar-auth-google#1]
I am trying to use the plugin but I'm getting this error while trying to login with Google ("Login with Google" blue button at the login page)

**You're not authorized to access this page. Please contact the administrator.**

I configure SonarQube v5.4 sonar.properties with this configuration:

sonar.auth.google.enabled=true
sonar.auth.google.allowUsersToSignUp=true
sonar.auth.google.clientId=&lt;my_google_client_id&gt;
sonar.auth.google.clientSecret=&lt;my_google_client_secret&gt;

Am I doing something wrong here?

![image](https://cloud.githubusercontent.com/assets/4641123/14250008/e6c9ad4a-fa52-11e5-8c99-c3eb7d8db26e.png)

![image](https://cloud.githubusercontent.com/assets/4641123/14250017/f32aa44a-fa52-11e5-9ec2-3e3b92b11d28.png)

Thanks in advance.

**Comment by steven-turner** [comment]
I was able to reproduce this behavior if the Default user group (sonar.defaultGroup) is set to a group that is not configured. Can you check if this is set to a valid user group?

**Comment by fhperuchi** [comment]
Hi Steven! Are you good?

I didn't have sonar.defaultGroup in my <SONAR_HOME>/conf/sonar.properties file. I tried to configure it like two ways below and I got the same error.

sonar.defaultGroup=sonar-users
sonar.defaultGroup=sonar-administrators

Do you have another suggestion?

Kind regards.

**Comment by steven-turner** [comment]
sonar-users is the default setting for this option, so that wasn't the problem...

I'll need some additional info to be of more help. Contact me via email if interested.

**Comment by aamirmushtaq** [comment]
I believe I might be late in this answer but I think that your oauth redirect on the google console page is incorrect. It should be : ${sonarBaseURL}/oauth2/callback/google and ${sonarBaseURL}/oauth2/callback
e.g. yourhost.tld/oauth2/callback

**Comment by iamrawtion** [comment]
> Hi Steven! Are you good?
> 
> I didn't have sonar.defaultGroup in my <SONAR_HOME>/conf/sonar.properties file. I tried to configure it like two ways below and I got the same error.
> 
> sonar.defaultGroup=sonar-users
> sonar.defaultGroup=sonar-administrators
> 
> Do you have another suggestion?
> 
> Kind regards.

Too late to ask. How did you fix this finally? I still get this issue. No fix available.
