### ISSUE TITLE
When signing in, redirected to insecure scheme

### ISSUE THREAD

**Issue by petemounce** [steven-turner/sonar-auth-google#5]
Using 0.5 of the plugin, when I sign in on https, I am redirected to the http version of the site. 

I expect to remain on https?

**Comment by steven-turner** [comment]
Yes. Can you verify that the your Google API credential setting for "Authorized redirect URIs" is configured on https?

**Comment by petemounce** [comment]
My Google API credential setting for "Authorized redirect URIs" is configured on https.

So is my `sonar.core.serverBaseURL`.

**Comment by steven-turner** [comment]
I think we tracked this down to an incorrect rewrite rule on the NGINX server in front of your Sonar instance. Ok to close this one?

**Comment by petemounce** [comment]
@steven-turner yes indeed. My nginx was not listening on port 80, and once I made it do that, with ssl on 443 (rather than `ssl on;`), this was fine.

Thanks very much for your help!

**Comment by petemounce** [comment]
So, I made the change to the nginx proxy (the configuration is attached below), but I am still redirected to an http scheme during the auth process.

(The capitalised parts below are tokens that are replaced during deployment). The flow _works_ now (as in, doesn't leave the user with a blank response because nothing's listening on 80), but leaves users on `http` while using the site.

``` nginx
server {
    listen          80;
    listen          443 ssl http2;
    server_name     RPL_SITE_NAME;

    ssl_certificate /ssl/RPL_SITE_SSL_DIR/RPL_SITE_SSL_CERT;
    ssl_certificate_key /ssl/RPL_SITE_SSL_DIR/RPL_SITE_SSL_KEY;
    ssl_session_timeout 5m;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    client_max_body_size 20M;

    # Optional optimisation - please refer to http://nginx.org/en/docs/http/configuring_https_servers.html
    # ssl_session_cache   shared:SSL:10m;
    location / {
        proxy_pass http://RPL_SITE_FQDN:RPL_SITE_PORT;
        proxy_redirect  off;
        proxy_set_header Host $host;
        proxy_request_buffering off;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
    }

   location /_nginx_status {
        stub_status on;
        access_log off;
        allow 127.0.0.1;
        deny all;
    }
}
```
